Repository advisors-excel-llc/ac-metadata-instructions, pull requests merged in 2023-09, with the labels that each got.

#86 defect/ac-44589 | Missing Contact Fields on the HouseholdPage layout | AC Package 1.5
  1.5.0
Labels: Approved

#81 defect/ac-46016 | Household field level security | AC Package 1.5
  1.5.0
Labels: Approved

#85 feature/ac 46595 | Remove old "create note" button from all layouts | AC Package 1.5
  1.5.0
Labels: Approved, Duo

#87 defect/ac-44589 | Missing Contact Fields and Remove field | AC Package 1.5
  1.5.0
Labels: Ready, Duo

#82 Feature/ac 24873 | Update 'Type' picklist | Ac package 1.5 | Patch
  1.5.1
Labels: Approved, Patch, Duo

#88 Feature/ac 23914 | Patch instruction to add new values and update the label | AC package 1.5
  1.5.1
Labels: Approved, Patch, Duo

#89 Feature/attribute change | picklistOperation to Operation in the exist | AC Package 1.5
  1.5.0
Labels: Approved, Duo

#75 Feature/ac 24629 | Path instruction to Create new “Meeting Outcome” picklist field | AC Package 1.5
  1.5.1
Labels: Approved, Patch, Duo

#92 feature/removeInstruction | Remove Instruction from 1.5.0 | AC package 1.5
  1.5.0
Labels: Ready, Duo

#91 feature/ac-46595 | Remove old "create note" button from all layouts | AC Package 1.5
  1.5.2
Labels: Ready, Patch, Duo

#84 Feature/ac 1813 | instructions for adding matching rules to duplicate rule for the merge tool
  1.5.0
Labels: Ready, Duo

#90 feature/ac-46397 | Replace old notes component with new version on all page layouts
  1.5.0
Labels: Ready, Duo
