Repository advisors-excel-llc/ac-metadata-instructions, pull requests merged in 2024-11, with the labels that each got.

#153 Defect/ac-62856 | Gearset - Contact - Object updates - Picklist options not visible
  1.9.0
Labels: Ready

#155 defect/ac-62886 | Defect - Unable to edit or create Dashboards
  1.9.0
Labels: Ready, Duo

#156 Defect/ac 62856 | Contact - Object updates - Picklist options not visible
  1.9.0
Labels: Approved

#157 Defect/ac 62886 | Create New Permission Set for Dashboard Create and Edit ability - unable to edit or create Dashboards
  1.9.0
Labels: Approved

#154 feature/ac-58903 | Gearest - Enable field history tracking for Account fields
  1.9.0
Labels: Ready

#158 Defect/removepremiumrecordtypes | Removing Record Type Assignments
  1.9.0
Labels: Ready

#159 Defect/ac-55368 | changing order of add remove operations for Alternative record type
  1.9.0
Labels: Ready
