Repository advisors-excel-llc/ac-metadata-instructions, pull requests merged in 2024-12, with the labels that each got.

#160 defect/ac-55368 | Update "Role" picklist values per Line of Business - Incorrect list on Alternative FA types
  1.9.0
Labels: Ready

#161 defect?ac-63969 | Person Account Record Type Label Not Updated to 'Client'
  1.9.0
Labels: Ready, Duo

#166 Defect/ac 64627 | Update Task Status Picklist
  1.9.0
Labels: Approved

#165 defect/ac-64577 | remove picklist values from accountcontactrelationship role
  1.9.0
Labels: Approved

#162 defect/ac-64312 | add source picklist values to record types
  1.9.0
Labels: Approved

#163 defect/ac-64578 | add/remove picklist values to campaign member & campaign objects
  1.9.0
Labels: Approved

#168 Feature/ac 64313 - Accout List Views
  1.9.0
Labels: Ready

#167 Defect/ac 63970 | Blank Org Testing - Missing Page Layout Assignments
  1.9.0
Labels: Ready, Duo

#169 defect/ac-63964 | Update Campaign Hierarchy FLS
  1.9.0
Labels: Ready
