Repository advisors-excel-llc/ac-metadata-instructions, pull requests merged in 2024-02, with the labels that each got.

#109 Develop => Main
  1.5.2
Labels: Ready

#110 feature/ac-51313 | Remove Notes related list from event layout
  1.5.0
  1.5.1
Labels: Ready

#111 Feature/ac 50792 | AC Package: Financial Account Object: DNU field Clean up
  1.6.0
Labels: Approved, Duo

#112 Defect/ac 52803 | Beta Testing: Estimate Net Worth field still being displayed
  1.5.0
Labels: Ready

#117 defect/ac-52811 | Remove old 'new note' quick action from layouts
  1.5.2
Labels: Ready, Duo

#118 Split up account task
  1.5.1
Labels: Ready
