Repository advisors-excel-llc/ac-metadata-instructions, pull requests merged in 2024-09, with the labels that each got.

#140 feature/ac-59247 | Gearset - Contact - Object updates
  1.9.0
Labels: Ready

#142 Feature/ac-59402 | Gearset - Opportunity update AllOpportunities list view
  1.9.0
Labels: Approved

#143 feature/ac-59410 | Gearset - Premium Picklist Values
  1.9.0
Labels: Approved

#147 feature/ac 60465 | Gearset - Disable Financial Account Role validation rule
  1.9.0
Labels: Ready, Duo

#144 feature/ac-60473 | Gearset - All Financial Accounts list view
  1.9.0
Labels: Ready

#145 feature/ac 59409 & feature/ac-59239 | Gearset Opportunity and Campaign Object Field History
  1.9.0
Labels: Ready, Duo

#149 feature/ac-61166 | Gearset - All Financial Accounts list view - Missing Product from list view
  1.9.0
Labels: Ready

#150 feature/ac 61139 | Gearset - Financial Account Field Sets
  1.9.0
Labels: Ready
