Repository advisors-excel-llc/ac-metadata-instructions, pull requests merged in 2024-08, with the labels that each got.

#136 Feature/ac 57412 | Gearset Instructions
  1.9.0
Labels: Ready, Duo

#138 feature/ac-57218 | Create instruction to update Activity Settings
  1.9.0
Labels: Ready, Duo

#134 feature/ac-58367 | Lead Object | add Today's Leads list view
  1.9.0
Labels: Approved

#137 Feature/ac 58366 | Campaign Hierarchy List View
  1.9.0
Labels: Approved

#139 Feature/ac 59235 | Gearset - Campaign Object - Add List Views
  1.9.0
Labels: Ready
